# ===============================
# = QUARKUS
# ===============================
quarkus:
  application:
    name: simple-auth-quarkus
  datasource:
    jdbc:
      max-size: 5
      min-size: 2
  hibernate-orm:
    database:
      generation: validate
  http:
    root-path: ${CONTEXT_PATH:/api}
  log:
    category:
      "sk.janobono.simple":
        level: ${LOG_LEVEL:DEBUG}
  mailer:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
  smallrye-jwt:
    enabled: false

# ===============================
# = APP
# ===============================
app:
  common:
    captcha-length: ${CAPTCHA_LENGTH:4}
    confirm-path: ${CONFIRM_PATH:/confirm/}
    mail: ${MAIL:simple@auth.org}
    web-url: ${WEB_URL:http://localhost:5173}
  auth:
    sign-up-token-expiration: ${SIGN_UP_TOKEN_EXPIRES_IN:1440}
    reset-password-token-expiration: ${RESET_PASSWORD_TOKEN_EXPIRES_IN:1440}
  jwt:
    issuer: ${TOKEN_ISSUER:simple}
    expiration: ${TOKEN_EXPIRES_IN:120}
  security:
    public-path-pattern-regex: ${SECURITY_PUBLIC_PATH_PATTERN_REGEX:^(/livez|/readyz|/captcha|/auth/(confirm|reset-password|sign-in|sign-up))$}
  verification:
    issuer: ${VERIFICATION_TOKEN_ISSUER:simple-verification}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}
    allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,OPTIONS,PATCH,DELETE}
    allowed-headers: ${CORS_ALLOWED_HEADERS:Authorization,Content-Type}
    allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}
    exposed-headers: ${CORS_EXPOSED_HEADERS:Authorization}

"%dev":
  quarkus:
    hibernate-orm:
      database:
        generation: drop-and-create

"%test":
  quarkus:
    hibernate-orm:
      database:
        generation: drop-and-create